version: 0.0
os: linux
files:
  - source: inst/aws/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: inst/aws/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: inst/aws/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: inst/aws/scripts/stop_server
      timeout: 300
      runas: root
